[package]
name = "cpi-reentrancy-vuln"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "cpi_reentrancy_vuln"

[dependencies]
anchor-lang = { workspace = true }
pinocchio = "0.10.1"

[features]
idl-build = ["anchor-lang/idl-build"]
