[package]
name = "signer-privilege-attacker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "signer_privilege_attacker"

[dependencies]
anchor-lang = { workspace = true }
pinocchio = "0.10.1"

[features]
idl-build = ["anchor-lang/idl-build"]
