[package]
name = "cpi-reentrancy-attacker"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30"


[lib]
crate-type = ["cdylib", "lib"]

[features]
idl-build = ["anchor-lang/idl-build"]
