[package]
name = "missing-account-vuln"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "missing_account_vuln"

[dependencies]
anchor-lang = { workspace = true }
pinocchio = { workspace = true }

[features]
idl-build = ["anchor-lang/idl-build"]
no-entrypoint = []
